////
Copyright 2024 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

[#hash_drgb]
:idprefix: hash_drbg_

= Hash-Based Deterministic Random Bit Generators

== Overview
Hash-based Deterministic Random Bit Generators (DRBGs) are cryptographic algorithms that produce a sequence of bits that appear random, but are deterministically generated from an initial seed.
These generators are crucial in cryptographic applications where predictability must be avoided and reproducibility is required given the same input.
The family of hash DRBGs implemented here leverages cryptographic hash functions to ensure security and randomness properties.
The design adheres to standards such as NIST SP 800-90A, which specifies requirements for deterministic random bit generators using hash functions.

== Security Considerations
The security of hash DRBGs is primarily dependent on the cryptographic strength of the underlying hash function used. The library supports several popular hash functions from the Boost.Crypt library, including SHA-256, SHA-512, and others.Users are encouraged to choose a hash function that meets their security requirements
Key security considerations include:

- Seed Quality: The initial seed must be sufficiently random and unpredictable. A poor quality seed can compromise the security of the generated bit sequence.
- Nonce Source: Ensure that you are inputting a nonce when instantiating the generator.
- Entropy Source: Ensure that the entropy source used to generate the seed is reliable and provides adequate entropy.
- Re-seeding: Regular reseeding with new entropy is recommended to maintain security, especially in long-running applications.

=== Prediction Resistance

Prediction resistance refers to the ability of a random number generator to resist attacks that attempt to predict future outputs based on past outputs.
A cryptographically secure RNG should be designed in such a way that even if an attacker has observed all previous outputs, they cannot reliably predict future outputs.

See NIST SP 800-90A if you are concerned about approved sources of entropy and nonces.

== Reference

[source, c++]
----
namespace boost {
namespace crypt {

namespace drbg {

template <bool prediction_resistance>
using sha1_hash_drbg_t = hash_drbg<sha1_hasher, 128U, 160U, prediction_resistance>;

} // namespace drbg

BOOST_CRYPT_EXPORT using sha1_hash_drbg = drbg::sha1_hash_drbg_t<false>;
BOOST_CRYPT_EXPORT using sha1_hash_drbg_pr = drbg::sha1_hash_drbg_t<true>;

// So on for each hasher available with te correct presets

namespace drbg {

// Max hasher security is defined in NIST SP 800-57 Table 3:
// See: https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57pt1r5.pdf
//
// 112: None
// 128: SHA-1
// 192: SHA-224, SHA-512/224, SHA3-224
// 256: SHA-256, SHA-512/256, SHA-384, SHA-512, SHA3-256, SHA3-384, SHA3-512
//
// Outlen is defined in NIST SP 800-90A Rev 1 Section 10.1 table 2
// 160: SHA-1
// 224: SHA-224, SHA-512/224
// 256: SHA-256, SHA-512/256
// 384: SHA-384
// 512: SHA-512
template <typename HasherType, boost::crypt::size_t max_hasher_security, boost::crypt::size_t outlen, bool prediction_resistance>
class hash_drbg
{
public:

    BOOST_CRYPT_GPU_ENABLED constexpr hash_drbg() noexcept = default;

    #ifdef BOOST_CRYPT_HAS_CXX20_CONSTEXPR
    BOOST_CRYPT_GPU_ENABLED constexpr ~hash_drbg() noexcept
    {
        destroy();
    }
    #endif

    template <typename ForwardIter1, typename ForwardIter2 = boost::crypt::uint8_t*, typename ForwardIter3 = boost::crypt::uint8_t*>
    BOOST_CRYPT_GPU_ENABLED constexpr auto init(ForwardIter1 entropy, boost::crypt::size_t entropy_size, ForwardIter2 nonce = nullptr, boost::crypt::size_t nonce_size = 0U, ForwardIter3 personalization = nullptr, boost::crypt::size_t personalization_size = 0U) noexcept -> state;

    template <typename Container1>
    BOOST_CRYPT_GPU_ENABLED constexpr auto init(const Container1& entropy) noexcept -> state;

    template <typename Container1, typename Container2>
    BOOST_CRYPT_GPU_ENABLED constexpr auto init(const Container1& entropy, const Container2& nonce) noexcept -> state;

    template <typename Container1, typename Container2, typename Container3>
    BOOST_CRYPT_GPU_ENABLED constexpr auto init(const Container1& entropy, const Container2& nonce, const Container3& personalization) noexcept -> state;

    #ifdef BOOST_CRYPT_HAS_STRING_VIEW
    constexpr auto init(std::string_view entropy) noexcept -> state;

    constexpr auto init(std::string_view entropy, std::string_view nonce) noexcept -> state;

    constexpr auto init(std::string_view entropy, std::string_view nonce, std::string_view personalization) noexcept -> state;
    #endif

    #ifdef BOOST_CRYPT_HAS_SPAN
    template <typename T, std::size_t extent>
    constexpr auto init(std::span<T, extent> entropy) noexcept -> state;

    template <typename T, std::size_t extent>
    constexpr auto init(std::span<T, extent> entropy, std::span<T, extent> nonce) noexcept -> state;

    template <typename T, std::size_t extent>
    constexpr auto init(std::span<T, extent> entropy, std::span<T, extent> nonce, std::span<T, extent> personalization) noexcept -> state;
    #endif

    template <typename ForwardIter1, typename ForwardIter2 = boost::crypt::uint8_t*>
    BOOST_CRYPT_GPU_ENABLED constexpr auto reseed(ForwardIter1 entropy, boost::crypt::size_t entropy_size,
                                                  ForwardIter2 additional_input = nullptr, boost::crypt::size_t additional_input_size = 0U) noexcept -> state;

    template <typename Container1>
    BOOST_CRYPT_GPU_ENABLED constexpr auto reseed(const Container1& entropy) noexcept -> state;

    template <typename Container1, typename Container2>
    BOOST_CRYPT_GPU_ENABLED constexpr auto reseed(const Container1& entropy, const Container2& additional_input) noexcept -> state;

    #ifdef BOOST_CRYPT_HAS_STRING_VIEW
    constexpr auto reseed(const std::string_view entropy) noexcept -> state;

    constexpr auto reseed(const std::string_view entropy, const std::string_view additional_input) noexcept -> state;
    #endif  // BOOST_CRYPT_HAS_STRING_VIEW

    #ifdef BOOST_CRYPT_HAS_SPAN
    template <typename T, std::size_t extent>
    constexpr auto reseed(std::span<T, extent> entropy) noexcept -> state;

    template <typename T, std::size_t extent>
    constexpr auto reseed(std::span<T, extent> entropy, std::span<T, extent> additional_input) noexcept -> state;
    #endif // BOOST_CRYPT_HAS_SPAN

    template <typename ForwardIter1, typename ForwardIter2 = boost::crypt::uint8_t*, typename ForwardIter3 = boost::crypt::uint8_t*>
    BOOST_CRYPT_GPU_ENABLED constexpr auto generate(ForwardIter1 data, boost::crypt::size_t requested_bits ForwardIter2 additional_data_1 = nullptr, boost::crypt::size_t additional_data_1_size = 0U, ForwardIter3 additional_data_2 = nullptr, boost::crypt::size_t additional_data_2_size = 0U) noexcept -> state;

    BOOST_CRYPT_GPU_ENABLED constexpr auto destroy() noexcept;
};

} // namespace drbg
} // namespace crypt
} // namespace boost

----
